########################################################
###### Config file for Kraken2 snakemake pipeline ######
########################################################

# Input FASTQ samples dir
samples.Dir:   /media/Disco11/pperaza/pperaza/pperaza-novogene/metagem_data/dataset/
metadata.File: /media/Disco9/jpereira/kraken_snake/metadata/metadata_metag_2025-4-10.csv
results.Dir:   /media/Disco11/pperaza/pperaza/Results/kraken_snake/MG1

#Fastqc Analysis
fastqc_analysis.rule: True
fastqc_analysis_paired.threads: 10

#Metadata validation
metadata_validation.rule : True
metadata_validation.file_separator: '\t'
metadata_validation.sample_id_column:  'LABID'
metadata_validation.fill_nan_values: 'median'
metadata_validation.paired: True

#Fastp
fastp.rule: True
fastp.threads_fastp: 10
fastp.jobs: 10
fastp.subsample: 20000000

#kraken2
kraken2.rule: True
kraken2.threads: 10
#kraken2.kraken2_db: "/home/pperaza/NOVOGENE/db/"
kraken2.kraken2_db: "/media/Disco11/pperaza/pperaza/pperaza-novogene/MG2/kraken2_db_cow-rumen_v1.0.1"

#Bracken
bracken.rule: True
bracken.bracken_db: "/media/Disco11/pperaza/pperaza/pperaza-novogene/MG2/kraken2_db_cow-rumen_v1.0.1" # Shoulb be inside a Kraken DataBase
bracken.read_length: 150
bracken.level: G
bracken.kraken_db_kmer: 35
bracken.threads: 10

#Merge Bracken
merge_bracken.rule: True
merge_bracken.level: 'G'
merge_bracken.metrics:
  - fraction_total_reads
  - new_est_reads

#DeSEQ2
deseq2.rule: True
deseq2.bracken_metric: 'new_est_reads'
deseq2.bracken_level: 'G'
deseq2.condition: 'Dieta'
deseq2.batch: ''
